### ISSUE TITLE
Use Config Vars For Token

### ISSUE THREAD

**Issue by RandomInventor** [The-bot-makers/Lichess-bot#10]
It will be good if implement config vars for token otherwise others might able to see our **token**
thanks.

**Comment by abhijato** [comment]
The problem with config vars, as far as I know, is that is is reset every time the dyno restarts. I thought of this, but after research, I found out that it resets with each dyno run, so it would not be good. Solution? private repo. Heroku can access private repos.

**Comment by abhijato** [comment]
If I am wrong about the problem, please tell me

**Comment by TheYoBots** [comment]
Well, config vars don’t restart every time a new deploy is done. Though I might have found a way to add a token using config vars, will test and commit :)
